const ANALYTICAL_BLUE_SCALE = ["#dbeafe", "#bfdbfe", "#93c5fd", "#60a5fa", "#3b82f6", "#2563eb"];
const ANALYTICAL_BLUE_STRONG = ["#bfdbfe", "#93c5fd", "#60a5fa", "#3b82f6", "#2563eb", "#1d4ed8"];

const ANALYTICAL_BLUE_DEEP = "#1d4ed8";
const ANALYTICAL_BLUE_ACCENT = "#2563eb";
const ANALYTICAL_BLUE_MID = "#3b82f6";
const ANALYTICAL_BLUE_SOFT = "#60a5fa";
const ANALYTICAL_BLUE_PALE = "#93c5fd";
const ANALYTICAL_BLUE_FAINT = "#dbeafe";

export {
  ANALYTICAL_BLUE_ACCENT,
  ANALYTICAL_BLUE_DEEP,
  ANALYTICAL_BLUE_FAINT,
  ANALYTICAL_BLUE_MID,
  ANALYTICAL_BLUE_PALE,
  ANALYTICAL_BLUE_SCALE,
  ANALYTICAL_BLUE_SOFT,
  ANALYTICAL_BLUE_STRONG,
};
